language: java
after_success: etc/travis-deploy.sh
sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'

env:
  global:
    - secure: "azTOm427TYgWCE/zGqQpSu1PU1w6CGF7noqKsxGkLMlj6tl4TDYVsywvywflFWnmOuhDykAIXiamBv/xh5RCef0P0ekfE4e9HKJ0+3NsTuqw/ecqeNv7ztT8H7KiM3cN+eRxl9jX4GiLBNoHIDc8v9913odbyXzRtwE/EViy8vI="
    - secure: "HWZdbiwuEjCViga0sk6SflAtmRgsQihV+mO0hsgLGK43MNxJS/7xQVPpSWKoaxd1Jd5nzAu5jg/7fy3cDZgviOjG3m8A9K5XvLwWa/ltq6gKu8qG+vY/miN5myOnT0U9Xs13awptCFz0Gm30tCJ7znxdPhMmQGBix1BNdM1XGRU="
